services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatbot-filmes-backend

    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=${GROQ_MODEL:-qwen/qwen3.8-27b}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatbot-filmes-frontend
    ports:
      - "5500:80"
    depends_on:
      - backend
    restart: unless-stopped